### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by NatashaSvic** [duckling-python-wrapper/fb_duckling#3]
Hi!

I have installed the original Fb-Duckling Haskell package and it runs correctly.
Also, I am able to load your python wrapper. However, when executing the code from the instruction, I get the following error:

<img width="747" alt="Screenshot 2019-08-16 at 11 48 01" src="https://user-images.githubusercontent.com/35193765/63159527-09f24380-c01c-11e9-86c5-5d79fdc97377.png">

Can you help?
Thanks a lot!!

**Comment by FellowNico** [comment]
Sorry for the late reply, but we forgot to add a call method to the Duckling class. Now it should work since it uses the request class method
