### ISSUE TITLE
TypeError: 'Duckling' object is not callable

### ISSUE THREAD

**Issue by farzinghanbari** [duckling-python-wrapper/fb_duckling#5]
I have installed duckling and I run 
```
from fb_duckling import Duckling
duckling = Duckling(locale="en_US")
```
successfully but when I run
```
duckling("All work and no play makes jack@gmail.com a dull boy 0102030405")
```

I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'Duckling' object is not callable
```
What is the problem?

**Comment by aolea** [comment]
You have to use duckling.request("All work and no play makes jack@gmail.com a dull boy 0102030405")

**Comment by farzinghanbari** [comment]
so please update the README file.

**Comment by aolea** [comment]
Im not the owner

**Comment by farzinghanbari** [comment]
Sorry, I didn't notice

**Comment by FellowNico** [comment]
Sorry for the late reply, we forgot to add the _call_ method to the Duckling class
